development:
      host: localhost
      adapter: mysql2
      database: fedena_ultimate
      port: 3306
      username: fedena
      password: password

test: &test
      host: localhost
      adapter: mysql2
      database: fedena_two_new
      port: 3306
      username: fedena
      password: password

production:
      host: localhost
      adapter: mysql2
      database: fedena_ultimate
      port: 3306
      username: fedena
      password: password
cucumber:
  <<: *test
